name: Build and deploy app.

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Installing my packages
        run: npm ci

      - name: Building App ..
        run: npm run build
        env:
          NEXT_PUBLIC_BASE_PATH: /portfolio-website
      - run: touch ./out/.nojekyll

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.2
        with:
          token: ${{ secrets.ROUTE }}
          repository-name: TH4KUR/TH4KUR.github.io
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: master # The branch the action should deploy to.
          FOLDER: out # The folder the action should deploy.
